In [21]:
import numpy as np
import pandas as pd
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

In [31]:
df = pd.read_csv('Dataset.csv')

In [32]:
ic=[]

for i in range(len(df['Loan Identifier'])):
    r=df.iloc[i,4]/1200
    p=df.iloc[i,-2]

    ic.append(p*r)   


df['Interest_Component']=ic

In [33]:
import pandas as pd

# Assuming you have a dataset in a DataFrame called 'df' with a column 'Loan_ID' that represents the loan identifier

# Group the data by Loan_ID
grouped_data = df.groupby('Loan Identifier')

# Initialize an empty list to store the filtered data
filtered_data = []

# Iterate over each group
for _, group in grouped_data:
    # Exclude the first six entries for each loan
    filtered_group = group.iloc[6:]
    filtered_data.append(filtered_group)

# Concatenate the filtered data back into a single DataFrame
filtered_df = pd.concat(filtered_data)

# Print the filtered loan data
filtered_df

,Loan Identifier,Monthly Reporting Period,Channel,Original Interest Rate,Current Interest Rate,Original UPB,Current Actual UPB,Original Loan Term,Origination Date,First Payment Date,...,High Balance Loan Indicator,Unemployment_rate,Divorce_rate,Inflation_rate,EMI,UPB_diff,Interest_Component,PREPAYMENT_AMT,Previous_UPB,Remaining MFM
1160807,97473062,12020,2,4.120,4.120,454000.0,450125.35,360,62019,82019,...,0,8.1,2.3,2.5,2198.991139,651.32,1547.666567,11.062194,450776.67,353
1160808,97473062,22020,2,4.120,4.120,454000.0,449471.79,360,62019,82019,...,0,8.1,2.3,2.3,2198.991139,653.56,1545.430368,13.302194,450125.35,352
1160809,97473062,32020,2,4.120,4.120,454000.0,448815.99,360,62019,82019,...,0,8.1,2.3,1.5,2198.991139,655.80,1543.186479,15.542194,449471.79,351
1160810,97473062,42020,2,4.120,4.120,454000.0,448815.99,360,62019,82019,...,0,8.1,2.3,0.3,2198.991139,0.00,1540.934899,0.000000,448815.99,350
1160811,97473062,52020,2,4.120,4.120,454000.0,448815.99,360,62019,82019,...,0,8.1,2.3,0.1,2198.991139,0.00,1540.934899,0.000000,448815.99,349
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
996753,999901768643,32019,2,3.625,3.625,226000.0,206555.78,240,92016,112016,...,0,3.7,2.7,1.9,1325.271935,699.19,626.082722,56.626398,207254.97,210
996754,999901768643,42019,2,3.625,3.625,226000.0,205854.48,240,92016,112016,...,0,3.7,2.7,2.0,1325.271935,701.30,623.970585,58.736398,206555.78,209
996755,999901768643,52019,2,3.625,3.625,226000.0,205151.06,240,92016,112016,...,0,3.7,2.7,1.8,1325.271935,703.42,621.852075,60.856398,205854.48,208
996756,999901768643,62019,2,3.625,3.625,226000.0,204445.52,240,92016,112016,...,0,3.7,2.7,1.6,1325.271935,705.54,619.727160,62.976398,205151.06,207
996757,999901768643,72019,2,3.625,0.000,226000.0,0.00,240,92016,112016,...,0,3.7,2.7,1.8,1325.271935,204445.52,0.000000,203802.956398,204445.52,206

In [34]:
filtered_df

,Loan Identifier,Monthly Reporting Period,Channel,Original Interest Rate,Current Interest Rate,Original UPB,Current Actual UPB,Original Loan Term,Origination Date,First Payment Date,...,High Balance Loan Indicator,Unemployment_rate,Divorce_rate,Inflation_rate,EMI,UPB_diff,Interest_Component,PREPAYMENT_AMT,Previous_UPB,Remaining MFM
1160807,97473062,12020,2,4.120,4.120,454000.0,450125.35,360,62019,82019,...,0,8.1,2.3,2.5,2198.991139,651.32,1547.666567,11.062194,450776.67,353
1160808,97473062,22020,2,4.120,4.120,454000.0,449471.79,360,62019,82019,...,0,8.1,2.3,2.3,2198.991139,653.56,1545.430368,13.302194,450125.35,352
1160809,97473062,32020,2,4.120,4.120,454000.0,448815.99,360,62019,82019,...,0,8.1,2.3,1.5,2198.991139,655.80,1543.186479,15.542194,449471.79,351
1160810,97473062,42020,2,4.120,4.120,454000.0,448815.99,360,62019,82019,...,0,8.1,2.3,0.3,2198.991139,0.00,1540.934899,0.000000,448815.99,350
1160811,97473062,52020,2,4.120,4.120,454000.0,448815.99,360,62019,82019,...,0,8.1,2.3,0.1,2198.991139,0.00,1540.934899,0.000000,448815.99,349
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
996753,999901768643,32019,2,3.625,3.625,226000.0,206555.78,240,92016,112016,...,0,3.7,2.7,1.9,1325.271935,699.19,626.082722,56.626398,207254.97,210
996754,999901768643,42019,2,3.625,3.625,226000.0,205854.48,240,92016,112016,...,0,3.7,2.7,2.0,1325.271935,701.30,623.970585,58.736398,206555.78,209
996755,999901768643,52019,2,3.625,3.625,226000.0,205151.06,240,92016,112016,...,0,3.7,2.7,1.8,1325.271935,703.42,621.852075,60.856398,205854.48,208
996756,999901768643,62019,2,3.625,3.625,226000.0,204445.52,240,92016,112016,...,0,3.7,2.7,1.6,1325.271935,705.54,619.727160,62.976398,205151.06,207
996757,999901768643,72019,2,3.625,0.000,226000.0,0.00,240,92016,112016,...,0,3.7,2.7,1.8,1325.271935,204445.52,0.000000,203802.956398,204445.52,206

In [35]:
# saving the dataframe
filtered_df.to_csv('FilteredDataset.csv', header=True, index=False)

In [29]:
filtered_df=filtered_df[filtered_df['Original UPB']!=filtered_df['Current Actual UPB']]

In [17]:
df.drop(['Loan Identifier','Monthly Reporting Period','First Time Home Buyer Indicator','Occupancy Status','Interest Only Loan Indicator','Modification Flag','Zero Balance Code','Special Eligibility Program','Property Valuation Method','High Balance Loan Indicator','EMI','UPB_diff','Interest_Component','PREPAYMENT_AMT','Remaining Months To Maturity'], axis=1, inplace = True)
df

,Channel,Original Interest Rate,Current Interest Rate,Original UPB,Current Actual UPB,Original Loan Term,Origination Date,First Payment Date,Original Loan to Value Ratio (LTV),Debt-To-Income (DTI),...,Property Type,Number of Units,Metropolitan Statistical Area (MSA),Zip Code Short,Current Loan Delinquency Status,Unemployment_rate,Divorce_rate,Inflation_rate,Previous_UPB,Remaining MFM
0,2,8.000,8.000,60000.0,60000.00,360,12000,32000,97,39.0,...,4,1,35660,491,0,4.0,4.0,3.2,60000.00,359
1,2,8.000,8.000,60000.0,60000.00,360,12000,32000,97,39.0,...,4,1,35660,491,0,4.0,4.0,3.8,60000.00,358
2,2,8.000,8.000,60000.0,60000.00,360,12000,32000,97,39.0,...,4,1,35660,491,0,4.0,4.0,3.1,60000.00,357
3,2,8.000,8.000,60000.0,60000.00,360,12000,32000,97,39.0,...,4,1,35660,491,0,4.0,4.0,3.2,60000.00,356
4,2,8.000,8.000,60000.0,60000.00,360,12000,32000,97,39.0,...,4,1,35660,491,0,4.0,4.0,3.7,60000.00,355
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
142982,2,2.125,2.125,227000.0,187959.24,144,122020,22021,46,25.0,...,3,1,15940,447,0,3.6,2.3,8.3,189873.88,124
142983,2,2.125,2.125,227000.0,186041.21,144,122020,22021,46,25.0,...,3,1,15940,447,0,3.6,2.3,8.2,187959.24,123
142984,2,2.125,2.125,227000.0,184119.79,144,122020,22021,46,25.0,...,3,1,15940,447,0,3.6,2.3,7.7,186041.21,122
142985,2,2.125,2.125,227000.0,182194.97,144,122020,22021,46,25.0,...,3,1,15940,447,0,3.6,2.3,7.1,184119.79,121
142986,2,2.125,2.125,227000.0,180266.74,144,122020,22021,46,25.0,...,3,1,15940,447,0,3.6,2.3,6.5,182194.97,120

In [10]:
df.head(60)

,Channel,Original Interest Rate,Current Interest Rate,Original UPB,Current Actual UPB,Original Loan Term,Origination Date,First Payment Date,Original Loan to Value Ratio (LTV),Debt-To-Income (DTI),...,Property Type,Number of Units,Metropolitan Statistical Area (MSA),Zip Code Short,Current Loan Delinquency Status,Unemployment_rate,Divorce_rate,Inflation_rate,Previous_UPB,Remaining MFM
0,2,8.0,8.0,60000.0,60000.00,360,12000,32000,97,39.0,...,4,1,35660,491,0,4.0,4.0,3.2,60000.00,359
1,2,8.0,8.0,60000.0,60000.00,360,12000,32000,97,39.0,...,4,1,35660,491,0,4.0,4.0,3.8,60000.00,358
2,2,8.0,8.0,60000.0,60000.00,360,12000,32000,97,39.0,...,4,1,35660,491,0,4.0,4.0,3.1,60000.00,357
3,2,8.0,8.0,60000.0,60000.00,360,12000,32000,97,39.0,...,4,1,35660,491,0,4.0,4.0,3.2,60000.00,356
4,2,8.0,8.0,60000.0,60000.00,360,12000,32000,97,39.0,...,4,1,35660,491,0,4.0,4.0,3.7,60000.00,355
5,2,8.0,8.0,60000.0,60000.00,360,12000,32000,97,39.0,...,4,1,35660,491,0,4.0,4.0,3.7,60000.00,354
6,2,8.0,8.0,60000.0,54978.70,360,12000,32000,97,39.0,...,4,1,35660,491,0,4.0,4.0,3.4,60000.00,353
7,2,8.0,8.0,60000.0,54125.33,360,12000,32000,97,39.0,...,4,1,35660,491,0,4.0,4.0,3.5,54978.70,352
8,2,8.0,8.0,60000.0,54125.33,360,12000,32000,97,39.0,...,4,1,35660,491,0,4.0,4.0,3.4,54125.33,351
9,2,8.0,8.0,60000.0,53941.85,360,12000,32000,97,39.0,...,4,1,35660,491,0,4.0,4.0,3.4,54125.33,350
10,2,8.0,8.0,60000.0,53598.67,360,12000,32000,97,39.0,...,4,1,35660,491,0,4.0,4.0,3.4,53941.85,349
11,2,8.0,8.0,60000.0,53246.56,360,12000,32000,97,39.0,...,4,1,35660,491,0,4.7,4.0,3.7,53598.67,348
12,2,8.0,8.0,60000.0,53068.75,360,12000,32000,97,39.0,...,4,1,35660,491,0,4.7,4.0,3.5,53246.56,347
13,2,8.0,8.0,60000.0,52839.75,360,12000,32000,97,39.0,...,4,1,35660,491,0,4.7,4.0,2.9,53068.75,346
14,2,8.0,8.0,60000.0,52839.75,360,12000,32000,97,39.0,...,4,1,35660,491,0,4.7,4.0,3.3,52839.75,345
15,2,8.0,8.0,60000.0,52659.23,360,12000,32000,97,39.0,...,4,1,35660,491,0,4.7,4.0,3.6,52839.75,344
16,2,8.0,8.0,60000.0,52400.00,360,12000,32000,97,39.0,...,4,1,35660,491,0,4.7,4.0,3.2,52659.23,343
17,2,8.0,8.0,60000.0,52191.54,360,12000,32000,97,39.0,...,4,1,35660,491,0,4.7,4.0,2.7,52400.00,342
18,2,8.0,8.0,60000.0,51856.69,360,12000,32000,97,39.0,...,4,1,35660,491,0,4.7,4.0,2.7,52191.54,341
19,2,8.0,8.0,60000.0,51500.00,360,12000,32000,97,39.0,...,4,1,35660,491,0,4.7,4.0,2.6,51856.69,340
20,2,8.0,8.0,60000.0,51200.00,360,12000,32000,97,39.0,...,4,1,35660,491,0,4.7,4.0,2.1,51500.00,339
21,2,8.0,8.0,60000.0,50850.00,360,12000,32000,97,39.0,...,4,1,35660,491,0,4.7,4.0,1.9,51200.00,338
22,2,8.0,8.0,60000.0,50500.00,360,12000,32000,97,39.0,...,4,1,35660,491,0,4.7,4.0,1.6,50850.00,337
23,2,8.0,8.0,60000.0,50150.00,360,12000,32000,97,39.0,...,4,1,35660,491,0,5.8,3.9,1.1,50500.00,336
24,2,8.0,8.0,60000.0,49750.00,360,12000,32000,97,39.0,...,4,1,35660,491,0,5.8,3.9,1.1,50150.00,335
25,2,8.0,8.0,60000.0,48700.00,360,12000,32000,97,39.0,...,4,1,35660,491,0,5.8,3.9,1.5,49750.00,334
26,2,8.0,8.0,60000.0,48700.00,360,12000,32000,97,39.0,...,4,1,35660,491,0,5.8,3.9,1.6,48700.00,333
27,2,8.0,8.0,60000.0,48250.00,360,12000,32000,97,39.0,...,4,1,35660,491,0,5.8,3.9,1.2,48700.00,332
28,2,8.0,8.0,60000.0,47450.00,360,12000,32000,97,39.0,...,4,1,35660,491,0,5.8,3.9,1.1,48250.00,331
29,2,8.0,8.0,60000.0,45750.00,360,12000,32000,97,39.0,...,4,1,35660,491,0,5.8,3.9,1.5,47450.00,330
30,2,8.0,8.0,60000.0,45750.00,360,12000,32000,97,39.0,...,4,1,35660,491,0,5.8,3.9,1.8,45750.00,329
31,2,8.0,8.0,60000.0,45200.00,360,12000,32000,97,39.0,...,4,1,35660,491,0,5.8,3.9,1.5,45750.00,328
32,2,8.0,8.0,60000.0,44650.00,360,12000,32000,97,39.0,...,4,1,35660,491,0,5.8,3.9,2.0,45200.00,327
33,2,8.0,8.0,60000.0,44400.00,360,12000,32000,97,39.0,...,4,1,35660,491,0,5.8,3.9,2.2,44650.00,326
34,2,8.0,8.0,60000.0,43900.00,360,12000,32000,97,39.0,...,4,1,35660,491,0,5.8,3.9,2.4,44400.00,325
35,2,8.0,8.0,60000.0,43000.00,360,12000,32000,97,39.0,...,4,1,35660,491,0,6.0,3.8,2.6,43900.00,324
36,2,8.0,8.0,60000.0,43000.00,360,12000,32000,97,39.0,...,4,1,35660,491,0,6.0,3.8,3.0,43000.00,323
37,2,8.0,8.0,60000.0,42500.00,360,12000,32000,97,39.0,...,4,1,35660,491,0,6.0,3.8,3.0,43000.00,322
38,2,8.0,8.0,60000.0,41900.00,360,12000,32000,97,39.0,...,4,1,35660,491,0,6.0,3.8,2.2,42500.00,321
39,2,8.0,8.0,60000.0,41000.00,360,12000,32000,97,39.0,...,4,1,35660,491,0,6.0,3.8,2.1,41900.00,320
40,2,8.0,8.0,60000.0,40800.00,360,12000,32000,97,39.0,...,4,1,35660,491,0,6.0,3.8,2.1,41000.00,319
41,2,8.0,8.0,60000.0,40500.00,360,12000,32000,97,39.0,...,4,1,35660,491,0,6.0,3.8,2.1,40800.00,318
42,2,8.0,8.0,60000.0,40332.67,360,12000,32000,97,39.0,...,4,1,35660,491,0,6.0,3.8,2.2,40500.00,317
43,2,8.0,0.0,60000.0,0.00,360,12000,32000,97,39.0,...,4,1,35660,491,100,6.0,3.8,2.3,40332.67,316
44,2,8.5,8.5,90000.0,90000.00,360,22000,42000,86,27.0,...,4,1,0,759,0,4.0,4.0,3.2,90000.00,360
45,2,8.5,8.5,90000.0,90000.00,360,22000,42000,86,27.0,...,4,1,0,759,0,4.0,4.0,3.8,90000.00,359
46,2,8.5,8.5,90000.0,90000.00,360,22000,42000,86,27.0,...,4,1,0,759,0,4.0,4.0,3.1,90000.00,358
47,2,8.5,8.5,90000.0,90000.00,360,22000,42000,86,27.0,...,4,1,0,759,0,4.0,4.0,3.2,90000.00,357
48,2,8.5,8.5,90000.0,90000.00,360,22000,42000,86,27.0,...,4,1,0,759,0,4.0,4.0,3.7,90000.00,356
49,2,8.5,8.5,90000.0,90000.00,360,22000,42000,86,27.0,...,4,1,0,759,0,4.0,4.0,3.7,90000.00,355
50,2,8.5,8.5,90000.0,89666.96,360,22000,42000,86,27.0,...,4,1,0,759,0,4.0,4.0,3.4,90000.00,354
51,2,8.5,8.5,90000.0,89666.96,360,22000,42000,86,27.0,...,4,1,0,759,0,4.0,4.0,3.5,89666.96,353
52,2,8.5,8.5,90000.0,89610.07,360,22000,42000,86,27.0,...,4,1,0,759,0,4.0,4.0,3.4,89666.96,352
53,2,8.5,8.5,90000.0,89552.78,360,22000,42000,86,27.0,...,4,1,0,759,0,4.0,4.0,3.4,89610.07,351
54,2,8.5,8.5,90000.0,89495.08,360,22000,42000,86,27.0,...,4,1,0,759,0,4.0,4.0,3.4,89552.78,350
55,2,8.5,8.5,90000.0,89378.46,360,22000,42000,86,27.0,...,4,1,0,759,0,4.7,4.0,3.7,89495.08,349
56,2,8.5,8.5,90000.0,89378.46,360,22000,42000,86,27.0,...,4,1,0,759,0,4.7,4.0,3.5,89378.46,348
57,2,8.5,8.5,90000.0,89319.53,360,22000,42000,86,27.0,...,4,1,0,759,0,4.7,4.0,2.9,89378.46,347
58,2,8.5,8.5,90000.0,89200.41,360,22000,42000,86,27.0,...,4,1,0,759,0,4.7,4.0,3.3,89319.53,346
59,2,8.5,8.5,90000.0,89200.41,360,22000,42000,86,27.0,...,4,1,0,759,0,4.7,4.0,3.6,89200.41,345

In [11]:
df2=df

In [5]:
df.columns

Index(['Channel', 'Original Interest Rate', 'Current Interest Rate',
       'Original UPB', 'Current Actual UPB', 'Original Loan Term',
       'Origination Date', 'First Payment Date',
       'Original Loan to Value Ratio (LTV)', 'Debt-To-Income (DTI)',
       'Borrower Credit Score at Origination', 'Loan Purpose', 'Property Type',
       'Number of Units', 'Metropolitan Statistical Area (MSA)',
       'Zip Code Short', 'Current Loan Delinquency Status',
       'Unemployment_rate', 'Divorce_rate', 'Inflation_rate', 'Previous_UPB',
       'Remaining MFM'],
      dtype='object')

In [12]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
X=df.drop(['Current Actual UPB'],axis=1)
y = df['Current Actual UPB']
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

In [13]:
X_train.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 114389 entries, 45226 to 113503
Data columns (total 21 columns):
 #   Column                                Non-Null Count   Dtype
---  ------                                --------------   -----
 0   Channel                               114389 non-null  int64
 1   Original Interest Rate                114389 non-null  float64
 2   Current Interest Rate                 114389 non-null  float64
 3   Original UPB                          114389 non-null  float64
 4   Original Loan Term                    114389 non-null  int64
 5   Origination Date                      114389 non-null  int64
 6   First Payment Date                    114389 non-null  int64
 7   Original Loan to Value Ratio (LTV)    114389 non-null  int64
 8   Debt-To-Income (DTI)                  114389 non-null  float64
 9   Borrower Credit Score at Origination  114389 non-null  float64
 10  Loan Purpose                          114389 non-null  int64
 11  Property Type                         114389 non-null  int64
 12  Number of Units                       114389 non-null  int64
 13  Metropolitan Statistical Area (MSA)   114389 non-null  int64
 14  Zip Code Short                        114389 non-null  int64
 15  Current Loan Delinquency Status       114389 non-null  int64
 16  Unemployment_rate                     114389 non-null  float64
 17  Divorce_rate                          114389 non-null  float64
 18  Inflation_rate                        114389 non-null  float64
 19  Previous_UPB                          114389 non-null  float64
 20  Remaining MFM                         114389 non-null  int64
dtypes: float64(9), int64(12)
memory usage: 19.2 MB

In [14]:
X_train

,Channel,Original Interest Rate,Current Interest Rate,Original UPB,Original Loan Term,Origination Date,First Payment Date,Original Loan to Value Ratio (LTV),Debt-To-Income (DTI),Borrower Credit Score at Origination,...,Property Type,Number of Units,Metropolitan Statistical Area (MSA),Zip Code Short,Current Loan Delinquency Status,Unemployment_rate,Divorce_rate,Inflation_rate,Previous_UPB,Remaining MFM
45226,2,5.750,5.750,120000.0,180,32006,52006,40,21.0,709.0,...,4,1,45300,346,0,8.9,3.6,3.2,62352.00,119
58904,1,5.250,5.250,103000.0,360,122009,22010,61,33.0,790.0,...,3,1,38060,852,0,8.1,3.4,1.7,95578.87,330
100925,1,2.750,2.750,108000.0,180,52013,72013,40,41.0,751.0,...,4,1,31080,917,0,7.4,3.3,1.2,108000.00,174
13680,2,6.500,6.500,25000.0,180,72002,92002,57,22.0,738.0,...,1,1,35620,107,0,5.3,3.1,0.5,3420.77,20
53432,2,7.625,7.625,83000.0,240,112008,12009,77,31.0,695.0,...,4,1,17460,442,0,6.2,3.2,0.8,67065.49,167
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6036,0,7.125,7.125,48000.0,180,32001,52001,80,29.0,769.0,...,4,1,26620,358,0,8.9,3.6,3.5,20019.75,53
95212,1,3.875,3.875,98000.0,360,112012,12013,70,45.0,677.0,...,0,1,33100,330,0,6.2,3.2,1.3,84947.63,336
51385,1,5.250,5.250,113000.0,180,42008,62008,29,49.0,694.0,...,4,2,47260,234,0,3.9,2.9,2.2,44475.29,53
115994,2,3.375,3.375,110000.0,180,12015,32015,39,20.0,804.0,...,4,1,42660,983,0,4.9,3.0,1.0,95954.54,164
113503,1,4.125,4.125,92000.0,180,92014,112014,78,23.0,731.0,...,4,1,18140,431,0,3.7,2.7,1.6,67198.68,123

In [15]:
y_train

45226      60592.78
58904      95428.26
100925    108000.00
13680       3021.19
53432      67065.49
            ...
6036       19703.82
95212      83761.44
51385      43038.11
115994     94844.77
113503     67198.68
Name: Current Actual UPB, Length: 114389, dtype: float64

In [38]:
model = Sequential()

model.add(Dense(units=64, activation='relu', input_dim=X.shape[1]))

model.add(Dense(units=32, activation='relu'))
model.add(Dense(units=16, activation='relu'))

model.add(Dense(units=1))

model.compile(optimizer='adam', loss='mean_absolute_error')

NameError: name 'X' is not defined

In [17]:
history = model.fit(X_train_scaled, y_train, epochs=50, batch_size=32)

Epoch 1/50
3575/3575 [==============================] - 12s 3ms/step - loss: 34505.9922
Epoch 2/50
3575/3575 [==============================] - 10s 3ms/step - loss: 5411.0874
Epoch 3/50
3575/3575 [==============================] - 10s 3ms/step - loss: 1769.5221
Epoch 4/50
3575/3575 [==============================] - 9s 3ms/step - loss: 1167.4445
Epoch 5/50
3575/3575 [==============================] - 11s 3ms/step - loss: 1048.0834
Epoch 6/50
3575/3575 [==============================] - 10s 3ms/step - loss: 1001.5566
Epoch 7/50
3575/3575 [==============================] - 10s 3ms/step - loss: 975.5723
Epoch 8/50
3575/3575 [==============================] - 10s 3ms/step - loss: 955.7341
Epoch 9/50
3575/3575 [==============================] - 10s 3ms/step - loss: 940.6508
Epoch 10/50
3575/3575 [==============================] - 11s 3ms/step - loss: 935.0995
Epoch 11/50
3575/3575 [==============================] - 10s 3ms/step - loss: 929.4947
Epoch 12/50
3575/3575 [==============================] - 10s 3ms/step - loss: 925.9711
Epoch 13/50
3575/3575 [==============================] - 11s 3ms/step - loss: 921.8020
Epoch 14/50
3575/3575 [==============================] - 11s 3ms/step - loss: 920.9595
Epoch 15/50
3575/3575 [==============================] - 11s 3ms/step - loss: 918.6744
Epoch 16/50
3575/3575 [==============================] - 10s 3ms/step - loss: 913.9945
Epoch 17/50
3575/3575 [==============================] - 10s 3ms/step - loss: 911.4578
Epoch 18/50
3575/3575 [==============================] - 10s 3ms/step - loss: 909.0172
Epoch 19/50
3575/3575 [==============================] - 10s 3ms/step - loss: 903.6708
Epoch 20/50
3575/3575 [==============================] - 10s 3ms/step - loss: 900.0702
Epoch 21/50
3575/3575 [==============================] - 10s 3ms/step - loss: 893.6469
Epoch 22/50
3575/3575 [==============================] - 10s 3ms/step - loss: 890.6837
Epoch 23/50
3575/3575 [==============================] - 10s 3ms/step - loss: 885.6742
Epoch 24/50
3575/3575 [==============================] - 10s 3ms/step - loss: 880.1867
Epoch 25/50
3575/3575 [==============================] - 10s 3ms/step - loss: 874.8901
Epoch 26/50
3575/3575 [==============================] - 10s 3ms/step - loss: 869.8215
Epoch 27/50
3575/3575 [==============================] - 10s 3ms/step - loss: 864.9514
Epoch 28/50
3575/3575 [==============================] - 10s 3ms/step - loss: 861.7586
Epoch 29/50
3575/3575 [==============================] - 10s 3ms/step - loss: 860.2958
Epoch 30/50
3575/3575 [==============================] - 10s 3ms/step - loss: 854.5225
Epoch 31/50
3575/3575 [==============================] - 10s 3ms/step - loss: 854.3021
Epoch 32/50
3575/3575 [==============================] - 10s 3ms/step - loss: 850.5850
Epoch 33/50
3575/3575 [==============================] - 10s 3ms/step - loss: 846.2401
Epoch 34/50
3575/3575 [==============================] - 9s 3ms/step - loss: 843.2860
Epoch 35/50
3575/3575 [==============================] - 10s 3ms/step - loss: 842.9626
Epoch 36/50
3575/3575 [==============================] - 10s 3ms/step - loss: 840.1592
Epoch 37/50
3575/3575 [==============================] - 10s 3ms/step - loss: 834.9439
Epoch 38/50
3575/3575 [==============================] - 10s 3ms/step - loss: 834.1780
Epoch 39/50
3575/3575 [==============================] - 10s 3ms/step - loss: 829.2178
Epoch 40/50
3575/3575 [==============================] - 10s 3ms/step - loss: 828.9908
Epoch 41/50
3575/3575 [==============================] - 10s 3ms/step - loss: 824.1870
Epoch 42/50
3575/3575 [==============================] - 10s 3ms/step - loss: 823.2599
Epoch 43/50
3575/3575 [==============================] - 10s 3ms/step - loss: 821.5156
Epoch 44/50
3575/3575 [==============================] - 10s 3ms/step - loss: 819.2096
Epoch 45/50
3575/3575 [==============================] - 9s 2ms/step - loss: 819.5945
Epoch 46/50
3575/3575 [==============================] - 14s 4ms/step - loss: 816.6688
Epoch 47/50
3575/3575 [==============================] - 10s 3ms/step - loss: 813.1722
Epoch 48/50
3575/3575 [==============================] - 10s 3ms/step - loss: 812.3387
Epoch 49/50
3575/3575 [==============================] - 10s 3ms/step - loss: 811.5400
Epoch 50/50
3575/3575 [==============================] - 10s 3ms/step - loss: 808.6661

In [37]:
predictions = model.predict(X_test_scaled)

NameError: name 'model' is not defined

In [36]:
print(predictions)

NameError: name 'predictions' is not defined

In [20]:
print(y_test)

77740     104841.11
107605    125584.24
4822       21627.19
138632     88438.09
56735      56697.94
            ...
12680      42943.57
32355      34143.69
2597       11574.71
18077      67929.34
94930      61425.10
Name: Current Actual UPB, Length: 28598, dtype: float64

In [21]:
from sklearn.metrics import mean_absolute_error
mean_absolute_error(predictions, y_test)

808.2127062340866

In [22]:
from sklearn.metrics import r2_score
print(r2_score(predictions, y_test))

0.9942522492051327

In [23]:
model.save("model_e100_newdata.h5")

In [24]:
import joblib
joblib.dump(scaler, 'scaler_newdata.joblib')

['scaler_newdata.joblib']

In [30]:
df2=pd.read_csv('TestPool.csv')
df2

,Loan Identifier,Monthly Reporting Period,Channel,Original Interest Rate,Current Interest Rate,Original UPB,Current Actual UPB,Original Loan Term,Origination Date,First Payment Date,...,Property Valuation Method,High Balance Loan Indicator,Unemployment_rate,Divorce_rate,Inflation_rate,EMI,UPB_diff,Interest_Component,Previous_UPB,Remaining MFM
0,122752190,22021,2,3.000,3.000,597000.0,597000.00,360,12021,32021,...,3,1,5.3,2.5,1.7,2516.976081,0.00,1492.500000,597000.00,359
1,122752190,32021,2,3.000,3.000,597000.0,596000.00,360,12021,32021,...,3,1,5.3,2.5,2.6,2516.976081,1000.00,1492.500000,597000.00,358
2,122752190,42021,2,3.000,3.000,597000.0,595000.00,360,12021,32021,...,3,1,5.3,2.5,4.2,2516.976081,1000.00,1492.500000,596000.00,357
3,122752190,52021,2,3.000,3.000,597000.0,594000.00,360,12021,32021,...,3,1,5.3,2.5,5.0,2516.976081,1000.00,1492.500000,595000.00,356
4,122752190,62021,2,3.000,3.000,597000.0,592000.00,360,12021,32021,...,3,1,5.3,2.5,5.4,2516.976081,2000.00,1492.500000,594000.00,355
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17005,128202561,82022,2,3.125,3.125,133000.0,130739.77,360,92021,112021,...,0,0,3.6,2.3,8.3,569.739351,228.68,346.354167,130968.45,349
17006,128202561,92022,2,3.125,3.125,133000.0,130510.50,360,92021,112021,...,0,0,3.6,2.3,8.2,569.739351,229.27,346.354167,130739.77,348
17007,128202561,102022,2,3.125,3.125,133000.0,130280.63,360,92021,112021,...,0,0,3.6,2.3,7.7,569.739351,229.87,346.354167,130510.50,347
17008,128202561,112022,2,3.125,3.125,133000.0,130050.16,360,92021,112021,...,0,0,3.6,2.3,7.1,569.739351,230.47,346.354167,130280.63,346
17009,128202561,122022,2,3.125,3.125,133000.0,129819.09,360,92021,112021,...,0,0,3.6,2.3,6.5,569.739351,231.07,346.354167,130050.16,345

In [31]:
ic=[]

for i in range(len(df2['Loan Identifier'])):
    r=df2.iloc[i,4]/1200
    p=df2.iloc[i,-2]

    ic.append(p*r)

In [32]:
df2['Interest_Component']=ic

In [33]:
df2

,Loan Identifier,Monthly Reporting Period,Channel,Original Interest Rate,Current Interest Rate,Original UPB,Current Actual UPB,Original Loan Term,Origination Date,First Payment Date,...,Property Valuation Method,High Balance Loan Indicator,Unemployment_rate,Divorce_rate,Inflation_rate,EMI,UPB_diff,Interest_Component,Previous_UPB,Remaining MFM
0,122752190,22021,2,3.000,3.000,597000.0,597000.00,360,12021,32021,...,3,1,5.3,2.5,1.7,2516.976081,0.00,1492.500000,597000.00,359
1,122752190,32021,2,3.000,3.000,597000.0,596000.00,360,12021,32021,...,3,1,5.3,2.5,2.6,2516.976081,1000.00,1492.500000,597000.00,358
2,122752190,42021,2,3.000,3.000,597000.0,595000.00,360,12021,32021,...,3,1,5.3,2.5,4.2,2516.976081,1000.00,1490.000000,596000.00,357
3,122752190,52021,2,3.000,3.000,597000.0,594000.00,360,12021,32021,...,3,1,5.3,2.5,5.0,2516.976081,1000.00,1487.500000,595000.00,356
4,122752190,62021,2,3.000,3.000,597000.0,592000.00,360,12021,32021,...,3,1,5.3,2.5,5.4,2516.976081,2000.00,1485.000000,594000.00,355
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17005,128202561,82022,2,3.125,3.125,133000.0,130739.77,360,92021,112021,...,0,0,3.6,2.3,8.3,569.739351,228.68,341.063672,130968.45,349
17006,128202561,92022,2,3.125,3.125,133000.0,130510.50,360,92021,112021,...,0,0,3.6,2.3,8.2,569.739351,229.27,340.468151,130739.77,348
17007,128202561,102022,2,3.125,3.125,133000.0,130280.63,360,92021,112021,...,0,0,3.6,2.3,7.7,569.739351,229.87,339.871094,130510.50,347
17008,128202561,112022,2,3.125,3.125,133000.0,130050.16,360,92021,112021,...,0,0,3.6,2.3,7.1,569.739351,230.47,339.272474,130280.63,346
17009,128202561,122022,2,3.125,3.125,133000.0,129819.09,360,92021,112021,...,0,0,3.6,2.3,6.5,569.739351,231.07,338.672292,130050.16,345

In [16]:
scaler.mean_[0]

67524.23508865132