In [1]:
import numpy as np
import pandas as pd
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

In [2]:
df = pd.read_csv('Dataset.csv')
df

,Loan Identifier,Monthly Reporting Period,Channel,Original Interest Rate,Current Interest Rate,Original UPB,Current Actual UPB,Original Loan Term,Origination Date,First Payment Date,...,High Balance Loan Indicator,Unemployment_rate,Divorce_rate,Inflation_rate,EMI,UPB_diff,Interest_Component,PREPAYMENT_AMT,Previous_UPB,Remaining MFM
0,100007365142,12000,2,8.000,8.000,75000.0,75000.00,360,121999,22000,...,0,4.0,4.0,2.7,550.323430,0.00,500.00,0.000000,75000.00,359
1,100007365142,22000,2,8.000,8.000,75000.0,75000.00,360,121999,22000,...,0,4.0,4.0,3.2,550.323430,0.00,500.00,0.000000,75000.00,358
2,100007365142,32000,2,8.000,8.000,75000.0,75000.00,360,121999,22000,...,0,4.0,4.0,3.8,550.323430,0.00,500.00,0.000000,75000.00,357
3,100007365142,42000,2,8.000,8.000,75000.0,75000.00,360,121999,22000,...,0,4.0,4.0,3.1,550.323430,0.00,500.00,0.000000,75000.00,356
4,100007365142,52000,2,8.000,8.000,75000.0,75000.00,360,121999,22000,...,0,4.0,4.0,3.2,550.323430,0.00,500.00,0.000000,75000.00,355
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1256463,105675700,112021,2,3.062,3.062,510000.0,500744.85,360,112020,12021,...,0,5.3,2.5,6.8,2167.271522,888.97,1301.35,23.048478,501633.82,348
1256464,105675700,122021,2,3.062,3.062,510000.0,499853.61,360,112020,12021,...,0,5.3,2.5,7.0,2167.271522,891.24,1301.35,25.318478,500744.85,347
1256465,105675700,12022,2,3.062,3.062,510000.0,498960.10,360,112020,12021,...,0,3.6,2.3,7.5,2167.271522,893.51,1301.35,27.588478,499853.61,346
1256466,105675700,22022,2,3.062,3.062,510000.0,498064.31,360,112020,12021,...,0,3.6,2.3,7.9,2167.271522,895.79,1301.35,29.868478,498960.10,345
1256467,105675700,32022,2,3.062,0.000,510000.0,0.00,360,112020,12021,...,0,3.6,2.3,8.5,2167.271522,498064.31,1301.35,497198.388478,498064.31,344

In [3]:
df.drop(['Loan Identifier','EMI','UPB_diff','Interest_Component','PREPAYMENT_AMT','Remaining Months To Maturity'], axis=1, inplace = True)

In [4]:
y= df['Current Actual UPB']

In [5]:
df.drop(['Current Actual UPB'], axis=1, inplace = True)

In [6]:
df['Current Actual UPB'] = y

In [7]:
df

,Monthly Reporting Period,Channel,Original Interest Rate,Current Interest Rate,Original UPB,Original Loan Term,Origination Date,First Payment Date,Original Loan to Value Ratio (LTV),Debt-To-Income (DTI),...,Zero Balance Code,Special Eligibility Program,Property Valuation Method,High Balance Loan Indicator,Unemployment_rate,Divorce_rate,Inflation_rate,Previous_UPB,Remaining MFM,Current Actual UPB
0,12000,2,8.000,8.000,75000.0,360,121999,22000,79,62.0,...,0,0,4,0,4.0,4.0,2.7,75000.00,359,75000.00
1,22000,2,8.000,8.000,75000.0,360,121999,22000,79,62.0,...,0,0,4,0,4.0,4.0,3.2,75000.00,358,75000.00
2,32000,2,8.000,8.000,75000.0,360,121999,22000,79,62.0,...,0,0,4,0,4.0,4.0,3.8,75000.00,357,75000.00
3,42000,2,8.000,8.000,75000.0,360,121999,22000,79,62.0,...,0,0,4,0,4.0,4.0,3.1,75000.00,356,75000.00
4,52000,2,8.000,8.000,75000.0,360,121999,22000,79,62.0,...,0,0,4,0,4.0,4.0,3.2,75000.00,355,75000.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1256463,112021,2,3.062,3.062,510000.0,360,112020,12021,83,34.0,...,0,0,0,0,5.3,2.5,6.8,501633.82,348,500744.85
1256464,122021,2,3.062,3.062,510000.0,360,112020,12021,83,34.0,...,0,0,0,0,5.3,2.5,7.0,500744.85,347,499853.61
1256465,12022,2,3.062,3.062,510000.0,360,112020,12021,83,34.0,...,0,0,0,0,3.6,2.3,7.5,499853.61,346,498960.10
1256466,22022,2,3.062,3.062,510000.0,360,112020,12021,83,34.0,...,0,0,0,0,3.6,2.3,7.9,498960.10,345,498064.31
1256467,32022,2,3.062,0.000,510000.0,360,112020,12021,83,34.0,...,1,0,0,0,3.6,2.3,8.5,498064.31,344,0.00

In [8]:
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split

X=df.drop(['Current Actual UPB'],axis=1)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)
X_train_1,X_valid,y_train_1,y_valid=train_test_split(X_train,y_train,test_size=0.2)
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train_1)
X_test_scaled = scaler.transform(X_test)
X_valid_scaled=scaler.transform(X_valid)

In [9]:
X_train

,Monthly Reporting Period,Channel,Original Interest Rate,Current Interest Rate,Original UPB,Original Loan Term,Origination Date,First Payment Date,Original Loan to Value Ratio (LTV),Debt-To-Income (DTI),...,Modification Flag,Zero Balance Code,Special Eligibility Program,Property Valuation Method,High Balance Loan Indicator,Unemployment_rate,Divorce_rate,Inflation_rate,Previous_UPB,Remaining MFM
658457,22014,1,4.500,4.500,400000.0,360,122010,22011,74,27.0,...,0,0,0,4,0,6.2,3.2,1.1,379696.42,322
1221686,22022,2,3.500,3.500,152000.0,240,62020,82020,76,26.0,...,0,0,0,0,0,3.6,2.3,7.9,141447.74,220
267728,62007,2,4.375,4.375,42000.0,120,42004,62004,70,15.0,...,0,0,0,4,0,4.6,3.6,2.7,24783.44,82
1201498,112021,2,3.750,3.750,180000.0,360,12020,32020,55,32.0,...,0,0,0,0,0,5.3,2.5,6.8,174125.21,338
609086,102013,0,5.000,5.000,368000.0,360,22010,42010,80,17.0,...,0,0,0,4,0,7.4,3.3,1.0,347223.92,316
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
489126,122009,1,6.125,6.125,198000.0,360,22008,42008,90,47.0,...,0,0,0,4,0,9.3,3.5,2.7,192846.81,338
91564,42004,0,7.000,7.000,76000.0,360,52001,72001,67,49.0,...,0,0,0,4,0,5.5,3.7,2.3,73729.88,325
1066519,42018,2,3.990,3.990,106000.0,180,12018,32018,75,44.0,...,0,0,0,0,0,3.9,2.9,2.5,106000.00,177
416883,62014,0,6.750,6.750,88000.0,360,102006,122006,80,53.0,...,0,0,0,4,0,6.2,3.2,2.1,77182.92,268
17596,42002,2,8.125,8.125,67000.0,180,32000,52000,95,37.0,...,0,0,0,4,0,5.8,3.9,1.6,61191.07,155

In [10]:
y_train

658457     379093.54
1221686    141447.74
267728      24241.04
1201498    173835.74
609086     346695.18
             ...
489126     192105.27
91564       73654.34
1066519    106000.00
416883      77017.21
17596       61191.07
Name: Current Actual UPB, Length: 1005174, dtype: float64

In [11]:
model = Sequential()

model.add(Dense(units=30, activation='relu', input_dim=X.shape[1]))

# Added an additional hidden layers
model.add(Dense(units=64, activation='relu'))
model.add(Dense(units=32, activation='relu'))
model.add(Dense(units=16, activation='relu'))

model.add(Dense(units=1))

model.compile(optimizer='adam', loss='mean_absolute_error')

In [12]:
model.fit(X_train_scaled, y_train_1, epochs=2, batch_size=32)

Epoch 1/2
25130/25130 [==============================] - 115s 4ms/step - loss: 4757.9282
Epoch 2/2
25130/25130 [==============================] - 81s 3ms/step - loss: 554.7996

In [13]:
predictions = model.predict(X_test_scaled)

7853/7853 [==============================] - 23s 3ms/step

In [14]:
print(predictions)

[[1.2421757e-03]
 [1.8301203e+05]
 [1.4115709e+05]
 ...
 [6.1027684e+04]
 [9.6899414e+04]
 [2.2840794e+05]]

In [15]:
print(y_test)

18027          0.00
315436    182670.32
871364    141164.34
237527     81789.29
601536    150222.26
            ...
181796     51150.14
666417     90299.28
593392     60327.87
983880     96900.63
491226    228320.47
Name: Current Actual UPB, Length: 251294, dtype: float64

In [16]:
from sklearn.metrics import mean_absolute_error
mean_absolute_error(predictions, y_test)

458.73237796621555

In [17]:
from sklearn.metrics import r2_score
print(r2_score(predictions, y_test))

0.9994818059853874