In [1]:
import numpy as np
import pandas as pd
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

In [2]:
df = pd.read_csv('Dataset.csv')
df

,Loan Identifier,Monthly Reporting Period,Channel,Original Interest Rate,Current Interest Rate,Original UPB,Current Actual UPB,Original Loan Term,Origination Date,First Payment Date,...,High Balance Loan Indicator,Unemployment_rate,Divorce_rate,Inflation_rate,EMI,UPB_diff,Interest_Component,PREPAYMENT_AMT,Previous_UPB,Remaining MFM
0,100007365142,12000,2,8.000,8.000,75000.0,75000.00,360,121999,22000,...,0,4.0,4.0,2.7,550.323430,0.00,500.00,0.000000,75000.00,359
1,100007365142,22000,2,8.000,8.000,75000.0,75000.00,360,121999,22000,...,0,4.0,4.0,3.2,550.323430,0.00,500.00,0.000000,75000.00,358
2,100007365142,32000,2,8.000,8.000,75000.0,75000.00,360,121999,22000,...,0,4.0,4.0,3.8,550.323430,0.00,500.00,0.000000,75000.00,357
3,100007365142,42000,2,8.000,8.000,75000.0,75000.00,360,121999,22000,...,0,4.0,4.0,3.1,550.323430,0.00,500.00,0.000000,75000.00,356
4,100007365142,52000,2,8.000,8.000,75000.0,75000.00,360,121999,22000,...,0,4.0,4.0,3.2,550.323430,0.00,500.00,0.000000,75000.00,355
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1256463,105675700,112021,2,3.062,3.062,510000.0,500744.85,360,112020,12021,...,0,5.3,2.5,6.8,2167.271522,888.97,1301.35,23.048478,501633.82,348
1256464,105675700,122021,2,3.062,3.062,510000.0,499853.61,360,112020,12021,...,0,5.3,2.5,7.0,2167.271522,891.24,1301.35,25.318478,500744.85,347
1256465,105675700,12022,2,3.062,3.062,510000.0,498960.10,360,112020,12021,...,0,3.6,2.3,7.5,2167.271522,893.51,1301.35,27.588478,499853.61,346
1256466,105675700,22022,2,3.062,3.062,510000.0,498064.31,360,112020,12021,...,0,3.6,2.3,7.9,2167.271522,895.79,1301.35,29.868478,498960.10,345
1256467,105675700,32022,2,3.062,0.000,510000.0,0.00,360,112020,12021,...,0,3.6,2.3,8.5,2167.271522,498064.31,1301.35,497198.388478,498064.31,344

In [3]:
df.drop(['EMI','UPB_diff','Interest_Component','PREPAYMENT_AMT','Remaining Months To Maturity', 'Loan Identifier'], axis=1, inplace = True)

In [4]:
y= df['Current Actual UPB']

In [5]:
df.drop(['Current Actual UPB'], axis=1, inplace = True)

In [6]:
df['Current Actual UPB'] = y

In [7]:
df

,Monthly Reporting Period,Channel,Original Interest Rate,Current Interest Rate,Original UPB,Original Loan Term,Origination Date,First Payment Date,Original Loan to Value Ratio (LTV),Debt-To-Income (DTI),...,Zero Balance Code,Special Eligibility Program,Property Valuation Method,High Balance Loan Indicator,Unemployment_rate,Divorce_rate,Inflation_rate,Previous_UPB,Remaining MFM,Current Actual UPB
0,12000,2,8.000,8.000,75000.0,360,121999,22000,79,62.0,...,0,0,4,0,4.0,4.0,2.7,75000.00,359,75000.00
1,22000,2,8.000,8.000,75000.0,360,121999,22000,79,62.0,...,0,0,4,0,4.0,4.0,3.2,75000.00,358,75000.00
2,32000,2,8.000,8.000,75000.0,360,121999,22000,79,62.0,...,0,0,4,0,4.0,4.0,3.8,75000.00,357,75000.00
3,42000,2,8.000,8.000,75000.0,360,121999,22000,79,62.0,...,0,0,4,0,4.0,4.0,3.1,75000.00,356,75000.00
4,52000,2,8.000,8.000,75000.0,360,121999,22000,79,62.0,...,0,0,4,0,4.0,4.0,3.2,75000.00,355,75000.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1256463,112021,2,3.062,3.062,510000.0,360,112020,12021,83,34.0,...,0,0,0,0,5.3,2.5,6.8,501633.82,348,500744.85
1256464,122021,2,3.062,3.062,510000.0,360,112020,12021,83,34.0,...,0,0,0,0,5.3,2.5,7.0,500744.85,347,499853.61
1256465,12022,2,3.062,3.062,510000.0,360,112020,12021,83,34.0,...,0,0,0,0,3.6,2.3,7.5,499853.61,346,498960.10
1256466,22022,2,3.062,3.062,510000.0,360,112020,12021,83,34.0,...,0,0,0,0,3.6,2.3,7.9,498960.10,345,498064.31
1256467,32022,2,3.062,0.000,510000.0,360,112020,12021,83,34.0,...,1,0,0,0,3.6,2.3,8.5,498064.31,344,0.00

In [8]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
X = df.iloc[:, :30]  
y = df.iloc[:, 30]  
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

In [9]:
y_train

1159318    375000.00
463197     320537.41
82808       81918.05
1195207    268514.31
1199934    318428.89
             ...
1017074    179293.69
768434     161932.89
683950     161613.09
693464      49732.03
5309        98908.39
Name: Current Actual UPB, Length: 1005174, dtype: float64

In [12]:
model = Sequential()

model.add(Dense(units=64, activation='relu', input_dim=X.shape[1]))

model.add(Dense(units=16, activation='relu'))

model.add(Dense(units=1))

model.compile(optimizer='adam', loss='mean_absolute_error' )

In [13]:
model.fit(X_train, y_train, epochs=3, batch_size=32)

Epoch 1/3
31412/31412 [==============================] - 65s 2ms/step - loss: 3767.4448
Epoch 2/3
31412/31412 [==============================] - 67s 2ms/step - loss: 3449.0464
Epoch 3/3
31412/31412 [==============================] - 65s 2ms/step - loss: 3356.5381

In [14]:
predictions = model.predict(X_test)
predictions = np.clip(predictions, 0, None)

7853/7853 [==============================] - 10s 1ms/step

In [15]:
print(predictions)

[[154510.72 ]
 [ 25777.205]
 [128206.53 ]
 ...
 [126987.35 ]
 [268391.28 ]
 [ 23163.625]]

In [16]:
print(y_test)

221971     154407.70
1018451     26329.06
860752     128232.57
978587     170562.65
624780     404809.28
             ...
268146      65679.93
1093469    245047.47
1014479    126463.50
787340     267497.05
72982       23627.82
Name: Current Actual UPB, Length: 251294, dtype: float64

In [17]:
y_test= y_test.values

In [18]:
from sklearn.metrics import mean_absolute_error
mean_absolute_error(predictions, y_test)

3185.522800350086