In [18]:
import numpy as np
import pandas as pd
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

In [19]:
df = pd.read_csv('Dataset.csv')
df

,Loan Identifier,Monthly Reporting Period,Channel,Original Interest Rate,Current Interest Rate,Original UPB,Current Actual UPB,Original Loan Term,Origination Date,First Payment Date,...,High Balance Loan Indicator,Unemployment_rate,Divorce_rate,Inflation_rate,EMI,UPB_diff,Interest_Component,PREPAYMENT_AMT,Previous_UPB,Remaining MFM
0,100007365142,12000,2,8.000,8.000,75000.0,75000.00,360,121999,22000,...,0,4.0,4.0,2.7,550.323430,0.00,500.00,0.000000,75000.00,359
1,100007365142,22000,2,8.000,8.000,75000.0,75000.00,360,121999,22000,...,0,4.0,4.0,3.2,550.323430,0.00,500.00,0.000000,75000.00,358
2,100007365142,32000,2,8.000,8.000,75000.0,75000.00,360,121999,22000,...,0,4.0,4.0,3.8,550.323430,0.00,500.00,0.000000,75000.00,357
3,100007365142,42000,2,8.000,8.000,75000.0,75000.00,360,121999,22000,...,0,4.0,4.0,3.1,550.323430,0.00,500.00,0.000000,75000.00,356
4,100007365142,52000,2,8.000,8.000,75000.0,75000.00,360,121999,22000,...,0,4.0,4.0,3.2,550.323430,0.00,500.00,0.000000,75000.00,355
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1256463,105675700,112021,2,3.062,3.062,510000.0,500744.85,360,112020,12021,...,0,5.3,2.5,6.8,2167.271522,888.97,1301.35,23.048478,501633.82,348
1256464,105675700,122021,2,3.062,3.062,510000.0,499853.61,360,112020,12021,...,0,5.3,2.5,7.0,2167.271522,891.24,1301.35,25.318478,500744.85,347
1256465,105675700,12022,2,3.062,3.062,510000.0,498960.10,360,112020,12021,...,0,3.6,2.3,7.5,2167.271522,893.51,1301.35,27.588478,499853.61,346
1256466,105675700,22022,2,3.062,3.062,510000.0,498064.31,360,112020,12021,...,0,3.6,2.3,7.9,2167.271522,895.79,1301.35,29.868478,498960.10,345
1256467,105675700,32022,2,3.062,0.000,510000.0,0.00,360,112020,12021,...,0,3.6,2.3,8.5,2167.271522,498064.31,1301.35,497198.388478,498064.31,344

In [20]:
df.drop(['Loan Identifier','EMI','UPB_diff','Interest_Component','PREPAYMENT_AMT','Remaining Months To Maturity'], axis=1, inplace = True)

In [21]:
y= df['Current Actual UPB']

In [22]:
df.drop(['Current Actual UPB'], axis=1, inplace = True)

In [23]:
df['Current Actual UPB'] = y

In [24]:
df

,Monthly Reporting Period,Channel,Original Interest Rate,Current Interest Rate,Original UPB,Original Loan Term,Origination Date,First Payment Date,Original Loan to Value Ratio (LTV),Debt-To-Income (DTI),...,Zero Balance Code,Special Eligibility Program,Property Valuation Method,High Balance Loan Indicator,Unemployment_rate,Divorce_rate,Inflation_rate,Previous_UPB,Remaining MFM,Current Actual UPB
0,12000,2,8.000,8.000,75000.0,360,121999,22000,79,62.0,...,0,0,4,0,4.0,4.0,2.7,75000.00,359,75000.00
1,22000,2,8.000,8.000,75000.0,360,121999,22000,79,62.0,...,0,0,4,0,4.0,4.0,3.2,75000.00,358,75000.00
2,32000,2,8.000,8.000,75000.0,360,121999,22000,79,62.0,...,0,0,4,0,4.0,4.0,3.8,75000.00,357,75000.00
3,42000,2,8.000,8.000,75000.0,360,121999,22000,79,62.0,...,0,0,4,0,4.0,4.0,3.1,75000.00,356,75000.00
4,52000,2,8.000,8.000,75000.0,360,121999,22000,79,62.0,...,0,0,4,0,4.0,4.0,3.2,75000.00,355,75000.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1256463,112021,2,3.062,3.062,510000.0,360,112020,12021,83,34.0,...,0,0,0,0,5.3,2.5,6.8,501633.82,348,500744.85
1256464,122021,2,3.062,3.062,510000.0,360,112020,12021,83,34.0,...,0,0,0,0,5.3,2.5,7.0,500744.85,347,499853.61
1256465,12022,2,3.062,3.062,510000.0,360,112020,12021,83,34.0,...,0,0,0,0,3.6,2.3,7.5,499853.61,346,498960.10
1256466,22022,2,3.062,3.062,510000.0,360,112020,12021,83,34.0,...,0,0,0,0,3.6,2.3,7.9,498960.10,345,498064.31
1256467,32022,2,3.062,0.000,510000.0,360,112020,12021,83,34.0,...,1,0,0,0,3.6,2.3,8.5,498064.31,344,0.00

In [25]:
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split

X=df.drop(['Current Actual UPB'],axis=1)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

In [26]:
X_train

,Monthly Reporting Period,Channel,Original Interest Rate,Current Interest Rate,Original UPB,Original Loan Term,Origination Date,First Payment Date,Original Loan to Value Ratio (LTV),Debt-To-Income (DTI),...,Modification Flag,Zero Balance Code,Special Eligibility Program,Property Valuation Method,High Balance Loan Indicator,Unemployment_rate,Divorce_rate,Inflation_rate,Previous_UPB,Remaining MFM
766037,82014,1,3.625,3.625,294000.0,360,12013,32013,80,22.0,...,0,0,0,4,0,6.2,3.2,1.7,286271.59,341
455034,102013,1,6.250,6.250,65000.0,240,62007,82007,46,33.0,...,0,0,0,4,0,7.4,3.3,1.0,52562.59,164
28579,112000,2,8.750,8.750,90000.0,360,22000,52000,72,41.0,...,0,0,0,4,0,4.0,4.0,3.4,89683.59,351
546192,62010,2,4.250,4.250,150000.0,336,22009,42009,56,21.0,...,0,0,0,4,0,9.6,3.6,1.1,143555.51,320
68905,112002,2,7.500,7.500,144000.0,360,22001,42001,70,21.0,...,0,0,0,4,0,5.8,3.9,2.2,141358.47,339
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
324219,62010,2,5.875,5.875,180000.0,360,52005,72005,80,30.0,...,0,0,0,4,0,9.6,3.6,1.1,165893.95,299
1100152,92019,2,4.375,4.375,127000.0,180,52018,72018,66,36.0,...,0,0,0,0,0,3.7,2.7,1.7,119825.52,164
557467,42012,1,4.750,4.750,237000.0,360,52009,72009,75,15.0,...,0,0,0,4,0,8.1,3.4,2.3,226510.75,325
758024,92016,0,3.625,0.000,486000.0,360,32013,52013,74,28.0,...,2,1,0,4,0,4.9,3.0,1.5,168741.48,318
309124,22006,2,5.375,5.375,220000.0,360,122004,22005,56,32.0,...,0,0,0,4,0,4.6,3.7,3.6,210707.50,346

In [27]:
y_train

766037     285794.85
455034      52361.25
28579       89629.50
546192     142915.12
68905      141238.58
             ...
324219     165617.48
1100152    119298.93
557467     226171.06
758024          0.00
309124     210251.51
Name: Current Actual UPB, Length: 1005174, dtype: float64

In [28]:
model = Sequential()

model.add(Dense(units=30, activation='relu', input_dim=X.shape[1]))

# Added an additional hidden layers
model.add(Dense(units=64, activation='relu'))
model.add(Dense(units=32, activation='relu'))
model.add(Dense(units=16, activation='relu'))

model.add(Dense(units=1))

model.compile(optimizer='adam', loss='mean_absolute_error')

In [29]:
model.fit(X_train_scaled, y_train, epochs=2, batch_size=32)

Epoch 1/2
31412/31412 [==============================] - 107s 3ms/step - loss: 3887.8369
Epoch 2/2
31412/31412 [==============================] - 107s 3ms/step - loss: 448.6658

In [30]:
predictions = model.predict(X_test_scaled)

7853/7853 [==============================] - 25s 3ms/step

In [31]:
print(predictions)

[[293157.62 ]
 [ 59310.766]
 [100637.59 ]
 ...
 [286199.53 ]
 [198356.72 ]
 [ 51602.957]]

In [32]:
print(y_test)

1096830    292816.48
285903      60000.00
370084     100582.24
79797      128260.57
853599     299000.00
             ...
521507     135362.67
213486      85295.36
627815     285913.16
1187088    198506.09
739171      51466.51
Name: Current Actual UPB, Length: 251294, dtype: float64

In [33]:
from sklearn.metrics import mean_absolute_error
mean_absolute_error(predictions, y_test)

389.5308762554555

In [34]:
from sklearn.metrics import r2_score
print(r2_score(predictions, y_test))

0.999350630643745